apiVersion: v1
kind: Service
metadata:
  name: memcached-sentry
  namespace: sentry
  labels:
    k8s-app: memcached-sentry
spec:
  ports:
  - name: memcache
    port: 11211
    targetPort: memcache
  - name: prometheus
    port: 9150
    targetPort: metrics
  selector:
    k8s-app: memcached-sentry
