apiVersion: monitoring.coreos.com/v1alpha1
kind: ServiceMonitor
metadata:
  name: memcached-sentry
  labels:
    k8s-app: memcached
  namespace: monitoring
spec:
  namespaceSelector:
    matchNames:
    - sentry
  jobLabel: k8s-app
  selector:
    matchLabels:
      k8s-app: memcached-sentry
  endpoints:
  - port: prometheus
    interval: 15s
