apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: es-data
  namespace: logging
  labels:
    component: elasticsearch
    role: data
    k8s-app: elasticsearch
spec:
  serviceName: es-data
  replicas: 2
  template:
    metadata:
      labels:
        component: elasticsearch
        role: data
        k8s-app: elasticsearch
      annotations:
        pod.beta.kubernetes.io/init-containers: '[
          {
          "name": "sysctl",
            "image": "busybox",
            "imagePullPolicy": "IfNotPresent",
            "command": ["sysctl", "-w", "vm.max_map_count=262144"],
            "securityContext": {
              "privileged": true
            }
          }
        ]'
    spec:
      containers:
      - name: es-data
        securityContext:
          privileged: true
          capabilities:
            add:
              - IPC_LOCK
        image: rosskukulinski/docker-elasticsearch-kubernetes-prometheus:5.2.1
        imagePullPolicy: Always
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: "CLUSTER_NAME"
          value: "services-us-east-2c-v1"
        - name: NODE_MASTER
          value: "false"
        - name: NETWORK_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: NODE_INGEST
          value: "false"
        - name: HTTP_ENABLE
          value: "true"
        - name: "ES_JAVA_OPTS"
          value: "-Xms1g -Xmx1g"
        ports:
        - containerPort: 9200
          name: http
          protocol: TCP
        - containerPort: 9300
          name: transport
          protocol: TCP
        volumeMounts:
        - name: storage
          mountPath: /data
        resources:
          requests:
            memory: "2Gi"
            cpu: "200m"
          limits:
            memory: "2Gi"
            cpu: "400m"
  volumeClaimTemplates:
  - metadata:
      name: storage
      annotations:
        volume.beta.kubernetes.io/storage-class: "default"
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 50Gi
