apiVersion: v1
kind: Service
metadata:
  name: redis-monitor
  namespace: sentry
  labels:
    app: redis-monitor
spec:
  ports:
  - name: prometheus
    port: 9121
    targetPort: metrics
  selector:
    app: redis-monitor
