apiVersion: monitoring.coreos.com/v1alpha1
kind: ServiceMonitor
metadata:
  name: redis-monitor
  labels:
    k8s-apps: redis
  namespace: monitoring
spec:
  namespaceSelector:
    matchNames:
    - sentry
  jobLabel: k8s-app
  selector:
    matchLabels:
      app: redis-monitor
  endpoints:
  - port: prometheus
    interval: 15s
