apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: sentry
  name: redis
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
  template:
    metadata:
      labels:
        name: redis
    spec:
      containers:
      - name: redis
        image: rosskukulinski/redis-kubernetes:v1.0.4
        ports:
        - containerPort: 6379
        resources:
          requests:
            memory: 500Mi
            cpu: 500m
          limits:
            memory: 500Mi
            cpu: 500m
        volumeMounts:
        - mountPath: /redis-master-data
          name: data
        livenessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: 5
          timeoutSeconds: 1
      volumes:
        - name: data
          emptyDir: {}
