apiVersion: v1
kind: Service
metadata:
  name: gateway
  labels:
    k8s-app: gateway
spec:
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
  selector:
    k8s-app: gateway
