apiVersion: v1
kind: Service
metadata:
  name: postgresql-sentry
  namespace: sentry
  labels:
    k8s-app: postgresql-sentry
spec:
  ports:
  - name: postgresql
    port: 5432
    targetPort: postgresql
  - name: prometheus
    port: 9187
    targetPort: metrics
  selector:
    k8s-app: postgresql-sentry
