apiVersion: v1
kind: Service
metadata:
  name: jenkins-discovery
  namespace: jenkins
spec:
  ports:
  - name: slaves
    port: 50000
    protocol: TCP
    targetPort: 50000
  selector:
    app: master
  type: LoadBalancer
