apiVersion: "stable.k8s.psg.io/v1"
kind: "Certificate"
metadata:
  name: "staging"
  namespace: staging
spec:
  domain: "clustername.staging.tld.com"
  email: "ross@kukulinski.com"
  provider: "googlecloud"
  secretName: "gateway-tls"
  altNames:
  - "prometheus.clustername.staging.tld.global"
