apiVersion: v1
kind: ServiceList
items:
  - apiVersion: v1
    kind: Service
    metadata:
      namespace: nexus
      name: nexus
    spec:
      sessionAffinity: None
      ports:
        - name: nexus
          port: 80
          targetPort: 8081
      selector:
        app: nexus