kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sentry
  namespace: sentry
  labels:
    app: sentry
  annotations:
    volume.beta.kubernetes.io/storage-class: fast
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
