apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    k8s-app: kube-cert-manager
  name: kube-cert-manager
  namespace: kube-system
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        k8s-app: kube-cert-manager
      name: kube-cert-manager
    spec:
      containers:
      - args:
        - -class=
        - -data-dir=/var/lib/cert-manager
        - -acme-url=https://acme-v01.api.letsencrypt.org/directory
        env:
        - name: GCE_PROJECT
          value: XXXX
        image: rosskukulinski/kube-cert-manager:0.5.0-san
        imagePullPolicy: IfNotPresent
        name: kube-cert-manager
        volumeMounts:
        - mountPath: /var/lib/cert-manager
          name: data
      - image: rosskukulinski/kubectl-proxy:1.5.4
        imagePullPolicy: IfNotPresent
        name: kubectl-proxy
      volumes:
      - gcePersistentDisk:
          fsType: ext4
          pdName: kube-cert-manager
        name: data
