kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: kube-cert-manager
  namespace: kube-system
  annotations:
    volume.beta.kubernetes.io/storage-class: "default"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
